### ISSUE TITLE
Propojit stránku politika s webem Demagog.cz

### ISSUE THREAD

**Issue by suchoss** [cesko-digital/nasi-politici#2]
Na každé stránce politika má Demagog 4 ikony (pravda, nepravda, zavádějící a neověřitelné). Tuto informaci je potřeba spolu s jedním výrokem zobrazovat v boxu **Demagog** na stránce politika v Našich politicích.

Pro získání dat použijte GraphQL rozhraní - [api demagoga](https://demagog.cz/stranka/api-pro-vyvojare).

**Comment by suchoss** [comment]
Nově je přidaný demagog do backendu, takže stačí volat následovně backend:

api/v1/demagog/{osobaId}

**Comment by miiila** [comment]
Demagog přidán a funguje, zavírám issue.
