### ISSUE TITLE
Dockerize Frontend

### ISSUE THREAD

**Issue by goodhoko** [cesko-digital/nasi-politici#38]
Create a docker image for running the Frontend component with the ultimate goal of creating a single-command docker-compose setup for local development.

- [ ] any configuration should be read from environment variables especially URL of backend.
- [x] create a `Frontend/README.md` that will contain instructions on how to build the image (if any build args are available) and how to run it (what environment variables it expects to be set and on what the port the container will listen for incomming connections.

This is part of [the parent issue for creating local development setup](https://github.com/cesko-digital/nasi-politici/issues/41).

**Comment by miiila** [comment]
Fixed by #37, closing an issue. Url via env variable will be added separately as there will be more ENV vars adjustments and parameters added.
