### ISSUE TITLE
Dockerize Backend

### ISSUE THREAD

**Issue by goodhoko** [cesko-digital/nasi-politici#39]
Create a docker image for running the Backend component (`NasiPolitici`) with the ultimate goal of creating a single-command docker-compose setup for local development.

- [ ] any configuration should be read from environment variables especially URL of MonitoraBackend.
- [ ] create a `NasiPolitici/README.md` that will contain instructions on how to build the image (if any build args are available) and how to run it (what environment variables it expects to be set and on what port the container will listen for incoming connections.

This is part of the [parent issue for creating local development setup](https://github.com/cesko-digital/nasi-politici/issues/41).

**Comment by miiila** [comment]
Done in https://github.com/cesko-digital/nasi-politici/pull/49.
