### ISSUE TITLE
Administrační sekce

### ISSUE THREAD

**Issue by suchoss** [cesko-digital/nasi-politici#4]
Rozšiřte volání Api Hlídače státu o základní administraci pro úpravu jednotlivých politiků. Pro inspiraci můžete nahlédnout na [návrh Administrace v Hlídači Státu](https://github.com/HlidacStatu/HlidacStatu/blob/master/Web.Statu/Controllers/ManageController.NasiPolitici.cs).

Jednotlivé views k administraci poté najdete tady:
[edit](https://github.com/HlidacStatu/HlidacStatu/blob/master/Web.Statu/Views/Manage/EditPersonNP.cshtml)
[find](https://github.com/HlidacStatu/HlidacStatu/blob/master/Web.Statu/Views/Manage/FindPerson.cshtml)
[create](
https://github.com/HlidacStatu/HlidacStatu/blob/master/Web.Statu/Views/Manage/CreatePerson.cshtml)
[detail](https://github.com/HlidacStatu/HlidacStatu/blob/master/Web.Statu/Views/Manage/PersonDetail.cshtml)

**Comment by miiila** [comment]
Zavírám po konzultaci s Tomášem Bajerem, mělo by být vyřešeno.
