### ISSUE TITLE
Nastylovat grafiku detailu podle šablony

### ISSUE THREAD

**Issue by suchoss** [cesko-digital/nasi-politici#5]
Je potřeba nastylovat detail politika podle šablony.

Backend si spustíte [podle návodu](https://github.com/cesko-digital/nasi-politici). V případě, že je potřeba měnit i html kód, tak je zapotřebí si spustit projekt.

**Comment by sigy** [comment]
**Profil politika pro mobil:**
https://app.avocode.com/view/8610fec9c2bc4f18bc8d8a1d7a88c5f7/_/comments

**Profil politika pro desktop:**
https://app.avocode.com/view/d3ae5185a1984a4283da72ea7714c126/_/comments

**Comment by sigy** [comment]
**Odkaz na všechny návrhy (včetně [komponent](https://app.avocode.com/view/17da08f8a866415295e685d71687da95/_/comments) a základního [style guide](https://app.avocode.com/view/14c2a0a6bc10487281cb47fa2df38035/_/comments), od kterých bych doporučoval začít:**
https://app.avocode.com/projects/1272420/groups/4646602

**Comment by miiila** [comment]
Zavírám po konzultaci s Tomášem Bajerem, mělo by být vyřešeno.
