### ISSUE TITLE
Nastylovat grafiku hledání podle šablony

### ISSUE THREAD

**Issue by suchoss** [cesko-digital/nasi-politici#6]
Je potřeba nastylovat detail politika podle šablony.

Backend si spustíte [podle návodu](https://github.com/cesko-digital/nasi-politici). V případě, že je potřeba měnit i html kód, tak je zapotřebí si spustit projekt.

**Comment by sigy** [comment]
> Je potřeba nastylovat **výsledky vyhledávání** podle šablony.

**Výsledky vyhledávání pro mobil:**
https://app.avocode.com/view/1f80edba921a41d395e5b0104a43d563/_/comments

**Výsledky vyhledávání pro desktop:**
https://app.avocode.com/view/b9b8f858047849d4a44923e5d14245d5/_/comments

**Comment by sigy** [comment]
**Odkaz na všechny návrhy (včetně [komponent](https://app.avocode.com/view/17da08f8a866415295e685d71687da95/_/comments) a základního [style guide](https://app.avocode.com/view/14c2a0a6bc10487281cb47fa2df38035/_/comments), od kterých bych doporučoval začít:**
https://app.avocode.com/projects/1272420/groups/4646602

**Comment by miiila** [comment]
Zavírám po konzultaci s Tomášem Bajerem, mělo by být vyřešeno.
