### ISSUE TITLE
Migrace Monitora-backend z Flask na AWS Lambda

### ISSUE THREAD

**Issue by martinwenisch** [cesko-digital/nasi-politici#65]
### Popis
V soucasne dobe mame na konzumaci API Monitory backend v Pythonu (projekt Monitora-backend), aktivne se pouziva jenom jako tenky klient pro samotne API, ale v blizke budoucnosti se pocita s jeho vyuzitim ve zpracovani a analyze textu clanku. Proto je vyhodne dal to oddelovat a pouzivat Python.

Kvuli uspore za infrastrukturu ho chceme zmigrovat z Flask (bezici v Dockeru) na AWS Lambda funkce (vyuzivajici serverless.com deployment) s definici endpointu na AWS API Gateway.

***Je potreba:***
- [ ] Vytvorit novy projekt s serverless.yml scriptem pro deployment vsech endpointu a jejich nastaveni na AWS API Gateway.
- [ ] Projit si jake endpointy se pouzivaji (nepouzivane jsou v master branch zakomentovane) a zmigrovat je na lambda funkce.

***Poznamky:***
- Monitora token se bere z ENV variable MONITORA_TOKEN a posila se v `headers={'Authorization': token_string}`
- Pro pomoc s nastavenim serverless.com (serverless.yml) se obratte na @martinwenisch na Slacku.

**Comment by Twista** [comment]
Ahoj, rad s tim pomuzu :) 

jeste otazka, je nejaky specialni duvod proc mit na kazdy API endopoint definici (aspon takhle jsem to pochopil). Vetsinou mi stacilo nasmerovat API gateway endpoint na / a pak resit routovani (nechat) ve Flasku - viz napriklad jako jsem popsal tady: https://medium.com/@Twistacz/flask-serverless-api-in-aws-lambda-the-easy-way-a445a8805028

**Comment by Twista** [comment]
koukam, ze jsem prehlidl ze chcete zmigrovat **z** Flasku - v PR jsem nechal pouzity Flask,
prijde mi to rozumny protoze to a) zna vetsina b) neni to vendor lock c) jednoduse se to vyviji lokalne

**Comment by martinwenisch** [comment]
Diky, variante s pouzitim Flasku v AWS Lambda se nebranim, ty pluginy vypadaji pekne. 

V zadani sem to nezminil, protoze s pouzitim celeho backend stacku v Lambde mam pomerne spatne zkusenosti. Temer zadna featura toho frameworku se tam nepouzije a pridava se level komplexity.

Ted si to projdu, pridam Github action deployment script a zkusim to nasadit.

**Comment by Twista** [comment]
jasny, dej kdyztak vedet jestli muzu pomoci :)
